### PR TITLE
Pinned the tool versions on the containers.

### PR DESCRIPTION
**Pull request by mberacochea**
The main change is on checkm, swapped to micomambra as with conda the env was not resolving.

I haven't tested the containers.

### CODE REVIEW

**Review by KeteSakharova — APPROVED** [review]
I just though maybe we need to have a template of Dockerfile somewhere. I usually forget to add versions to vars..
Thank you, Martin, for fixing that!

**Review by tgurbich — CHANGES_REQUESTED** [review]
Thank you, Martin! Looks great but I'd put the GTDB Dockerfile inside the 1.5.1 subfolder. Possibly other tools too if we know we need multiple versions (CheckM, for example)

**Comment by mberacochea** [comment]
> Thank you, Martin! Looks great but I'd put the GTDB Dockerfile inside the 1.5.1 subfolder. Possibly other tools too if we know we need multiple versions (CheckM, for example)

Yep, I'll do it for gtdbtk now. We can do the same for other tools as required

**Review by tgurbich — APPROVED** [review]
Thank you! Looks good.

**Review by KeteSakharova — APPROVED** [review]

**Pull request merged**
